version: 0.2
# Defining default values for all jobs updated file 4
defaults: &defaults
phases:
  pre_build:
    commands:
      #- npm install sfdx-cli --global
      #- npm update --global sfdx-cli
      - curl -fL https://getcli.jfrog.io | sh
  build:
    commands:
      - echo Build started...
      - echo $salesforceInstanceURL
      - echo $salesforceUserName
      - echo $salesforceClientId
      - echo $CODEBUILD_SOURCE_REPO_URL
      - echo $CODEBUILD_BUILD_NUMBER
      - echo $CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo $CODEBUILD_SOURCE_VERSION
      - echo $CODEBUILD_START_TIME
      - echo $CODEBUILD_SRC_DIR
      
      #- sfdx --help
      #- sfdx force:auth:jwt:grant --clientid $salesforceClientId --jwtkeyfile ./server.key --username $salesforceUserName --instanceurl $salesforceInstanceURL -a SIT
      #- sfdx force:mdapi:deploy -l RunLocalTests -c -d ./force-app/main/default/ -u SIT -w 10
      
  post_build:
    commands:
      #- ls $CODEBUILD_SRC_DIR
      - zip $CODEBUILD_SRC_DIR/MyBuild.zip -r $CODEBUILD_SRC_DIR * 
      #- ls $CODEBUILD_SRC_DIR
      - ./jfrog rt config --url https://sdc.jfrog.io/artifactory/ --user salesforce-ci --password AKCp5fTQixdiS5iECcdfqYug9kkW2CJUrb9GJz3MechLrfemcasce5cJXxG1RW1fLDd94rw5d --interactive=false
      - ./jfrog rt u $CODEBUILD_SRC_DIR/MyBuild.zip libs-release-local/ --build-name=QABuild --build-number=12345
      
 
